FROM node:12-alpine

#COPY ~/Users/dom/.aws/credentials /root/.aws/credentials

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install

COPY . .

CMD ["node", "./database/seed/pictures.seed.js"]

